# Generated by Django 4.1.7 on 2023-07-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='book',
            name='file_field',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
