# Generated by Django 4.1.7 on 2023-07-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file_field',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
