# Generated by Django 4.1.7 on 2023-07-14 23:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_book_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_uploaded',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
