# Generated by Django 4.1.7 on 2023-07-17 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0008_book_date_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_uploaded',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('book', 'creator')},
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the Blog', max_length=250, verbose_name='Blog Title')),
                ('contents', models.TextField(help_text='Blog contents', verbose_name='Blog Content')),
                ('date_created', models.DateTimeField(auto_now=True, help_text='Date Created', verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now_add=True, help_text='Date Updated')),
                ('images', models.ImageField(help_text='Image of the Blog', upload_to='Blog')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('user', models.ForeignKey(help_text='The user who created The blog', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Blog',
            },
        ),
    ]
